#  EDUNET FOUNDATION - Classroom Exercise Notebook

## Lab - 1 Basic Operation on Image Using cv2 


## Exercise-1 Image Reading in Different Types

In [1]:
import cv2
import numpy as np

In [2]:
image = cv2.imread("blur_kernel.jpg")

In [3]:
image

array([[[ 74,  71,  67],
        [ 75,  72,  68],
        [ 74,  71,  67],
        ...,
        [139, 131, 124],
        [123, 115, 108],
        [122, 114, 107]],

       [[ 72,  69,  65],
        [ 73,  70,  66],
        [ 73,  68,  65],
        ...,
        [137, 127, 120],
        [122, 112, 105],
        [120, 110, 103]],

       [[ 64,  61,  57],
        [ 66,  61,  58],
        [ 66,  61,  58],
        ...,
        [133, 117, 111],
        [119, 103,  97],
        [117, 101,  95]],

       ...,

       [[ 18,  84,  65],
        [ 15,  81,  62],
        [ 11,  77,  58],
        ...,
        [  3,  33,  14],
        [  4,  34,  15],
        [  5,  35,  16]],

       [[ 16,  85,  65],
        [ 15,  81,  62],
        [ 11,  77,  58],
        ...,
        [  3,  33,  14],
        [  4,  34,  15],
        [  5,  35,  16]],

       [[ 15,  83,  66],
        [ 12,  80,  63],
        [ 11,  76,  60],
        ...,
        [  6,  34,  15],
        [  7,  35,  16],
        [  8,  36,  17]]

### In the Second Parameter of cv2.imread("Source of Image ", below 3 options)
- cv2.IMREAD_COLOR: It specifies to load a color image. Any transparency of image will be neglected. It is the default flag. Alternatively, we can pass integer value 1 for this flag.
- cv2.IMREAD_GRAYSCALE: It specifies to load an image in grayscale mode. Alternatively, we can pass integer value 0 for this flag.
- cv2.IMREAD_UNCHANGED: It specifies to load an image as such including alpha channel. Alternatively, we can pass integer value -1 for this flag.


In [4]:
cv2.imshow("image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

## Exercise-2 Starting Video Camera

### Steps to capture a video:

- Use cv2.VideoCapture() to get a video capture object for the camera.
- Set up an infinite while loop and use the read() method to read the frames using the above created object.
- Use cv2.imshow() method to show the frames in the video.
- Breaks the loop when the user clicks a specific key.

In [11]:
# import the opencv library
import cv2
  
  
# define a video capture object
vid = cv2.VideoCapture(0)
  
while(True):
      
    # Capture the video frame
    # by frame
    ret, frame = vid.read()
  
    # Display the resulting frame
    cv2.imshow('frame', frame)
      
    # the 'q' button is set as the
    # quitting button you may use any
    # desired button of your choice
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
  
# After the loop release the cap object
vid.release()
# Destroy all the windows
cv2.destroyAllWindows()

## Exercise-3 Image Filter

In [6]:
import cv2
import numpy as np
image = cv2.imread("blur_kernel.jpg")

# Print error message if image is null
if image is None:
    print('Could not read image')

# Apply identity kernel
kernel1 = np.array([[7, 7, 7],
                    [0, 0, 0],
                    [7, 7, 7]])

identity = cv2.filter2D(src=image,  ddepth=-1,kernel=kernel1)


cv2.imshow('Original', image)
cv2.imshow('Identity', identity)
    
cv2.waitKey()
#cv2.imwrite('identity.jpg', identity)
cv2.destroyAllWindows()

In [ ]:
cv2.imshow('Original', image)
cv2.imshow('Identity', identity)
    
cv2.waitKey()
cv2.imwrite('identity.jpg', identity)
cv2.destroyAllWindows()


In [ ]:
# Apply blurring kernel
kernel2 = np.ones((5, 5), np.float32) / 25
img = cv2.filter2D(src=image, ddepth=-1, kernel=kernel2)

cv2.imshow('Original', image)
cv2.imshow('Kernel Blur', img)
    
cv2.waitKey()
cv2.imwrite('blur_kernel.jpg', img)
cv2.destroyAllWindows()

In [7]:
b,g,r=cv2.split(image)

In [8]:
b

array([[ 74,  75,  74, ..., 139, 123, 122],
       [ 72,  73,  73, ..., 137, 122, 120],
       [ 64,  66,  66, ..., 133, 119, 117],
       ...,
       [ 18,  15,  11, ...,   3,   4,   5],
       [ 16,  15,  11, ...,   3,   4,   5],
       [ 15,  12,  11, ...,   6,   7,   8]], dtype=uint8)

In [12]:
b=b*0

In [17]:
g

array([[37, 37, 37, ..., 69, 61, 61],
       [36, 36, 36, ..., 68, 61, 60],
       [32, 33, 33, ..., 66, 59, 58],
       ...,
       [ 9,  7,  5, ...,  1,  2,  2],
       [ 8,  7,  5, ...,  1,  2,  2],
       [ 7,  6,  5, ...,  3,  3,  4]], dtype=uint8)

In [13]:
img=cv2.merge((b,g,r))

error: OpenCV(4.6.0) C:\b\abs_74oeeuevib\croots\recipe\opencv-suite_1664548340488\work\modules\core\src\merge.dispatch.cpp:129: error: (-215:Assertion failed) mv[i].size == mv[0].size && mv[i].depth() == depth in function 'cv::merge'


In [11]:
cv2.imshow('Original', img)
cv2.waitKey()
cv2.destroyAllWindows()
